#!/bin/bash

mkdir -p proto_generate

python -m grpc_tools.protoc \
    -I./protos \
    --python_out=proto_generate \
    --grpc_python_out=proto_generate \
    protos/**/*.proto

PYTHONPATH="$PWD/proto_generate:$PYTHONPATH"
python src/order_book/order_book_service.py
